#!/usr/bin/env python
# This file is automatically generated by pywf script
# based on the content in pyproject.toml file

__version__ = "0.1.1"
__short_description__ = "Sakura Gather"
__license__ = "Proprietary"
__author__ = "Angora King"
__author_email__ = "angoraking@email.com"
__maintainer__ = "Angora King"
__maintainer_email__ = "angoraking@email.com"

# run this script to print out the version number
if __name__ == "__main__":  # pragma: no cover
    print(__version__)
